<?php

namespace App\Models;

use Encore\Admin\Traits\DefaultDatetimeFormat;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Component extends Model
{
    use DefaultDatetimeFormat;
    use HasFactory;

    protected $fillable = [
        'category_id',
        'brand',
        'name',
        'aliasName',
        'quality',
        'supplier_id',
        'purchase_price',
        'stock',
        'is_finish'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::updating(function ($model) {
            if ($model->stock == 0) {
                $model->is_finish = !$model->is_finish;
            } else {
                $model->is_finish = true;
            }
        });
    }

    public function repairs()
    {
        return $this->belongsToMany(Repair::class,
            'repair_components', 'component_id', 'repair_id');
    }

    public function categories()
    {
        return $this->belongsToMany(Category::class,
            'component_categories', 'component_id', 'category_id');
    }
}
