<?php

namespace App\Models;

use Carbon\Carbon;
use Encore\Admin\Traits\DefaultDatetimeFormat;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Order extends Model
{
    use DefaultDatetimeFormat;
    use HasFactory;

    protected $primaryKey = 'order_id';
    public $incrementing = false;
    protected $keyType = 'string';
    protected $fillable = ['order_id', 'product_name', 'contact_name', 'phone_number', 'status', 'supplier_id', 'deposit', 'price'];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->order_id = static::generateOrderId();
        });
    }

    public function repairs()
    {
        return $this->belongsToMany(Repair::class,
            'order_repairs', 'order_id', 'repair_id');
    }

    public function supplier()
    {
        return $this->belongsTo(Supplier::class);
    }

    protected static function generateOrderId(): string
    {
        $prefix = 'MBO';
        $postfix = Str::substr(Carbon::now()->getPreciseTimestamp(4), -5, 5);
        return $prefix . Carbon::now()->year . $postfix;
    }
}

